// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odyksappeylfvwibwaii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9keWtzYXBwZXlsZnZ3aWJ3YWlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5ODQzMjUsImV4cCI6MjA2NjU2MDMyNX0.apespzn_OFQBwzvvT6f1gUWmBWjyzUatVFw5XsrUJH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);